import type { NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";

const Home: NextPage = () => {
  const session = useSession();
  console.log(session);
  return (
    <div>
      <Head>
        <title>NextAuth.js Spotify example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Hello{" "}
          {session.status === "authenticated"
            ? session.data.user?.name || "friend"
            : "stranger"}
        </h1>
        <p>
          {session.status === "authenticated" ? (
            <button type="button" onClick={() => signOut()}>
              Sign out {session.data.user?.email}
            </button>
          ) : (
            <button
              type="button"
              onClick={() => signIn("spotify")}
              disabled={session.status === "loading"}
            >
              Sign in with Spotify
            </button>
          )}
        </p>
      </main>
    </div>
  );
};

export default Home;
