import type { NextPage } from "next";
import Head from "next/head";

import { Login } from "components/Login";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>NextAuth.js Spotify example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Login />
      </main>
    </div>
  );
};

export default Home;
